# Generated by Django 3.2.14 on 2022-07-27 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='begin_time',
            new_name='speech_begin_time',
        ),
        migrations.AddField(
            model_name='speaker',
            name='speech_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
