# Generated by Django 3.2.14 on 2022-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0003_auto_20220730_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='name',
            field=models.CharField(default=555, max_length=50),
            preserve_default=False,
        ),
    ]
