# Generated by Django 3.2.14 on 2022-07-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0004_speaker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(max_length=2048),
        ),
    ]
