# Generated by Django 3.2.14 on 2022-07-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0005_alter_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='block',
            field=models.CharField(default=555, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='time_gap',
            field=models.CharField(default=555, max_length=10),
            preserve_default=False,
        ),
    ]
