# Generated by Django 3.2.14 on 2022-07-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0006_auto_20220730_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='time_gap',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
