# Generated by Django 3.2.14 on 2022-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0007_alter_speaker_time_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='telegram_id',
            field=models.CharField(max_length=15),
        ),
    ]
